/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArchivesSlugRouteImport } from './routes/archives.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardArchiveIdRouteImport } from './routes/dashboard.$archiveId'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as DashboardArchiveIdAnalyticsRouteImport } from './routes/dashboard.$archiveId_.analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesSlugRoute = ArchivesSlugRouteImport.update({
  id: '/archives/$slug',
  path: '/archives/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArchiveIdRoute = DashboardArchiveIdRouteImport.update({
  id: '/$archiveId',
  path: '/$archiveId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArchiveIdAnalyticsRoute =
  DashboardArchiveIdAnalyticsRouteImport.update({
    id: '/$archiveId_/analytics',
    path: '/$archiveId/analytics',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/archives/$slug': typeof ArchivesSlugRoute
  '/dashboard/$archiveId': typeof DashboardArchiveIdRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$archiveId/analytics': typeof DashboardArchiveIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/archives/$slug': typeof ArchivesSlugRoute
  '/dashboard/$archiveId': typeof DashboardArchiveIdRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$archiveId/analytics': typeof DashboardArchiveIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/archives/$slug': typeof ArchivesSlugRoute
  '/dashboard/$archiveId': typeof DashboardArchiveIdRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$archiveId_/analytics': typeof DashboardArchiveIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/archives/$slug'
    | '/dashboard/$archiveId'
    | '/dashboard/new'
    | '/dashboard/'
    | '/dashboard/$archiveId/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/archives/$slug'
    | '/dashboard/$archiveId'
    | '/dashboard/new'
    | '/dashboard'
    | '/dashboard/$archiveId/analytics'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/archives/$slug'
    | '/dashboard/$archiveId'
    | '/dashboard/new'
    | '/dashboard/'
    | '/dashboard/$archiveId_/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ArchivesSlugRoute: typeof ArchivesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives/$slug': {
      id: '/archives/$slug'
      path: '/archives/$slug'
      fullPath: '/archives/$slug'
      preLoaderRoute: typeof ArchivesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$archiveId': {
      id: '/dashboard/$archiveId'
      path: '/$archiveId'
      fullPath: '/dashboard/$archiveId'
      preLoaderRoute: typeof DashboardArchiveIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$archiveId_/analytics': {
      id: '/dashboard/$archiveId_/analytics'
      path: '/$archiveId/analytics'
      fullPath: '/dashboard/$archiveId/analytics'
      preLoaderRoute: typeof DashboardArchiveIdAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardArchiveIdRoute: typeof DashboardArchiveIdRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardArchiveIdAnalyticsRoute: typeof DashboardArchiveIdAnalyticsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardArchiveIdRoute: DashboardArchiveIdRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardArchiveIdAnalyticsRoute: DashboardArchiveIdAnalyticsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ArchivesSlugRoute: ArchivesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
